### ISSUE TITLE
ppt file

### ISSUE THREAD

**Issue by mikeshams** [vyhoangquocnguyen/CapstoneProject_G1#1]
Modify the ppt file to explain how to test the components

**Comment by ManuSimriti** [comment]
[](url)
[Uploading Components.pptx…]()
This is the newly updated presentation of the hardware components testing.

**Comment by ManuSimriti** [comment]
[Components.pptx](https://github.com/vyhoangquocnguyen/CapstoneProject_G1/files/6649889/Components.pptx)

**Comment by mikeshams** [comment]
Add process of testing for the camera as well as the water level sensor

**Comment by ManuSimriti** [comment]
I will add that in the ppt file. Thank you

**Comment by ManuSimriti** [comment]
Hi Sir, below is the updated ppt file which includes the testing of all the remaining components.
[Components.pptx](https://github.com/vyhoangquocnguyen/CapstoneProject_G1/files/6688377/Components.pptx)
