### ISSUE TITLE
Demonstration

### ISSUE THREAD

**Issue by mikeshams** [vyhoangquocnguyen/CapstoneProject_G1#2]
1) Show the remaining components
2) Test them in class

**Comment by ManuSimriti** [comment]
Dear Sir, 
We have received the following components which will further be tested in the class:
1)Large Breadboard
2)Electronics Toolkit
3)Compact Switching Power Supply - Selectable Output 3-12VDC
4)Stereo Enclosed Speaker Set - 3W 4 Ohm
5)Raspberry Pi 4 Model B - 4 GB RAM
6)Ultra-Flexible White LED Strip - 480 LED per meter - 1m long - - Cool White ~6000K
7)Ultrasonic sensor to detect Water level
8)HUMIDITY & TEMPERATURE SENSOR BR
9)TUBING PVC 8MM ID X 1 METER
10)Peristaltic Liquid Pump with Silicone Tubing - 12V DC Power.
11)USB camera

Apart from these components, there are three more components which we are yet to arrive:
1)Adafruit STEMMA Soil Sensor - I2C Capacitive Moisture Sensor 
The component is currently out of stock and we are trying to get it from other sources.

2)i2c / SPI character LCD backpack & Standard LCD 16x2 + extras - white on blue
This LCD is an Alternative to HDMI which is OUT OF STOCK. So this component we are searching to get from the websites and will hopefully get it soon.

3)Plastic Water Solenoid Valve - 12V - 1/2" Nominal
This component is also Out of Stock and we looking for a substitute and/or other sources to get the original product.

**Comment by mikeshams** [comment]
Please demonstrate testing:
Raspberry Pi 4 Model B - 4 GB RAM
Ultrasonic sensor to detect Water level
Peristaltic Liquid Pump with Silicone Tubing - 12V DC Power.
USB camera
Adafruit STEMMA Soil Sensor
i2c / SPI character LCD backpack & Standard LCD 16x2
Plastic Water Solenoid Valve - 12V - 1/2" Nominal

**Comment by ManuSimriti** [comment]
Noted sir, I will demonstrate the rest of the components as soon as I receive them. Thank you

**Comment by ManuSimriti** [comment]
Hi Sir, the components will be received by me on 23rd June between (9:30Am- 4:30am) from DHL. Below is the screenshot of the delivery information.![image](https://user-images.githubusercontent.com/61207294/122796562-88f5da00-d28c-11eb-9c17-7680ee81d9b6.png)

**Comment by mikeshams** [comment]
I have updated the milestone.

**Comment by ManuSimriti** [comment]
Hi Sir, I have tracked the shipment and the delivery shows by the end of today. Below is the screenshot attached. ![image](https://user-images.githubusercontent.com/61207294/123171651-192d4e00-d44a-11eb-9859-e4ca428199e9.png)

**Comment by ManuSimriti** [comment]
Hi Sir, I have tracked the shipment and the delivery shows by the end of today. Below is the screenshot attached. The shipment is under clearance that means it may take 2-3 days for customer to process and clear the transaction in order to deliver the shipment. ![image](https://user-images.githubusercontent.com/61207294/123309574-176b9500-d4f3-11eb-85f3-697378255a5f.png)

**Comment by mikeshams** [comment]
Have you received them finally?

**Comment by ManuSimriti** [comment]
Not yet sir. As mentioned in the screenshot, the shipment is under clearance event which may take 2-3 days to process the delivery. I will notify you as soon as I receive them.

**Comment by ManuSimriti** [comment]
![WhatsApp Image 2021-06-28 at 12 49 08](https://user-images.githubusercontent.com/61207294/123674146-46de1280-d80f-11eb-8544-c4058888b9b0.jpeg)

**Comment by ManuSimriti** [comment]
Hi Sir, I have received the remaining components today and will be ready to demonstrate the testing in the coming class. Thank you
