### ISSUE TITLE
Water Level Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [vyhoangquocnguyen/CapstoneProject_G1#6]
Demonstrate this task!

**Comment by vyhoangquocnguyen** [comment]
Hi sir, we are still waiting to receive the sensor, hopefully it will be delivered today

**Comment by vyhoangquocnguyen** [comment]
Hi sir, it's ready to demonstrate. Should I upload the result pictures?

**Comment by vyhoangquocnguyen** [comment]
sorry i misclick the "close issue"

**Comment by mikeshams** [comment]
Demonstrate it on Monday!

**Comment by vyhoangquocnguyen** [comment]
ready sir
