### ISSUE TITLE
LCD Display Interfacing

### ISSUE THREAD

**Issue by mikeshams** [vyhoangquocnguyen/CapstoneProject_G1#7]
1. How to change the font size from 5*8 to 5*10 or vice versa?
2. Demonstrate your task

**Comment by vyhoangquocnguyen** [comment]
1. Most HD44780 based and similar LCDs have two areas for the fonts, the GCROM, and the GCRAM. the GCROM is not editable as this is written by the manufacturer, while the GCRAM allows for user-defined characters. This area allows the user to define 8 characters and is usually used for custom symbols. I found this link as tutorial to help with changing the font https://www.handsonembedded.com/lcd16x2-hd44780-tutorial-5/ 
2.  Waiting for testing components then we can demonstrate them

**Comment by vyhoangquocnguyen** [comment]
1. and this tutorial as well https://www.instructables.com/Custom-Large-Font-For-16x2-LCDs/

**Comment by vyhoangquocnguyen** [comment]
2nd Issue: the C code I searched is not working properly, I'm writing my own code in C language to test it again. Also, the LCD and the I2C backpack is working fine with python code

**Comment by mikeshams** [comment]
Waiting!

**Comment by vyhoangquocnguyen** [comment]
ready to be demostrated sir
