### ISSUE TITLE
Moisture Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [vyhoangquocnguyen/CapstoneProject_G1#8]
Demonstrate your task

**Comment by ManuSimriti** [comment]
Noted sir, I received the sensor today and will interface and demonstrate it in the next class.

**Comment by ManuSimriti** [comment]
Hi sir, I have been trying to interface the soil sensor with raspberry pi from the day I received the component (July 5th). It seems like the sensor is not being detected by the host. Below are the pictures showing no detection. I also tested it with Arduino Uno, the sensor showed no output although got detected by Arduino Uno.
![WhatsApp Image 2021-07-07 at 11 27 25 (1)](https://user-images.githubusercontent.com/61207294/124787896-dfaf1500-df16-11eb-9617-d107b237a0ec.jpeg)
![WhatsApp Image 2021-07-07 at 11 27 25](https://user-images.githubusercontent.com/61207294/124787911-e2aa0580-df16-11eb-8494-63751b00df80.jpeg)

**Comment by ManuSimriti** [comment]
Hi Sir, I have discussed with my group mates and we came to know that the current sensor is not working. So we have ordered the new sensor from Walmart which will take hardly one day to collect. Below is the order confirmation.![image](https://user-images.githubusercontent.com/61207294/125329019-ff797b00-e312-11eb-8778-10ed134ae2ce.png)

**Comment by mikeshams** [comment]
When will you receive the component?

**Comment by ManuSimriti** [comment]
The Capacitive Sensor has arrived. I will test it and will demonstrate in the next class.

**Comment by mikeshams** [comment]
Find a viable solution to interface the sensor to the MCU!

**Comment by ManuSimriti** [comment]
The sensor is working as I have interfaced it with Raspberry Pi through Arduino successfully. However, I need time to interface it with ADC board. I will demonstrate my task within this week. https://user-images.githubusercontent.com/61207294/127054210-1d0a4e98-c9b2-4e11-985e-c7f6b01f561d.MOV

**Comment by mikeshams** [comment]
ok

**Comment by mikeshams** [comment]
go with the arduino then
